### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by georgevarghese185** [oreshinya/purescript-crypto#1]
Some functions (like aes256 deciphering) can throw runtime exceptions if it fails. But these functions don't indicate the possibility of run time exceptions which can be dangerous. Could it be added?

**Comment by oreshinya** [comment]
Right.
But next update will be using `Effect` monad instead of `Eff` monad for 0.12.
So i do not add EXCEPTION of `Effect` kind now.
Thank you for your comment :)
