### ISSUE TITLE
Since node version 11 createCipher has been deprecated

### ISSUE THREAD

**Issue by cscalfani** [oreshinya/purescript-crypto#9]
Running with node 11+ displays the following message when `createCipher` is called:

```
(node:60770) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
The deprecated function:

```js
crypto.createDecipher(algorithm, password[, options])
```

has been replaced with:

```js
crypto.createCipheriv(algorithm, key, iv[, options])
```

Looks like they added the `iv`, which is the [initialization vector](https://en.wikipedia.org/wiki/Initialization_vector). This could simply be a random number converted into a `String`.

**Comment by oreshinya** [comment]
@hivemind-js 
Thank you very much, and sorry for late response.
I'll check it day after tomorrow.
